server:
  port: 8080

spring:
  application:
    name: short

  datasource:
    url: ${DB_URL:jdbc:postgresql://pg-313d3567-vanhunglekhiet-3d8a.l.aivencloud.com:17778/youtube}
    username: ${DB_USER:avnadmin}
    password: ${DB_PASSWORD:}

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_schema: youtube

  flyway:
    enabled: false
    baseline-on-migrate: true
    locations: classpath:db/migration
    schemas: youtube
    default-schema: youtube

youtube:
  api:
    key: ${YOUTUBE_API_KEY:}